# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - loadgenerator.yaml # During development, the loadgenerator module inside skaffold.yaml will be used.
resources:
- adservice.yaml
- cartservice.yaml
- checkoutservice.yaml
- currencyservice.yaml
- emailservice.yaml
- frontend.yaml
- paymentservice.yaml
- productcatalogservice.yaml
- recommendationservice.yaml
- shippingservice.yaml
# components:
# - ../kustomize/components/cymbal-branding
# - ../kustomize/components/google-cloud-operations
# - ../kustomize/components/memorystore
# - ../kustomize/components/network-policies
# - ../kustomize/components/alloydb
# - ../kustomize/components/shopping-assistant
# - ../kustomize/components/spanner
# - ../kustomize/components/container-images-tag
# - ../kustomize/components/container-images-tag-suffix
# - ../kustomize/components/container-images-registry

# images:
# - name: vicv369/adservice
#   newTag: '8'
# - name: vicv369/frontend-demo
#   newTag: '8'
images:
- name: vicv369/adservice
  newName: vicv369/adservice
  newTag: v34
- name: vicv369/checkoutservice
  newName: vicv369/checkoutservice
  newTag: v34
- name: vicv369/currencyservice
  newName: vicv369/currencyservice
  newTag: v34
- name: vicv369/emailservice
  newName: vicv369/emailservice
  newTag: v34
- name: vicv369/frontend
  newName: vicv369/frontend
  newTag: v34
- name: vicv369/loadgenerator
  newName: vicv369/loadgenerator
  newTag: v34
- name: vicv369/paymentservice
  newName: vicv369/paymentservice
  newTag: v34
- name: vicv369/productcatalogservice
  newName: vicv369/productcatalogservice
  newTag: v34
- name: vicv369/recommendationservice
  newName: vicv369/recommendationservice
  newTag: v34
- name: vicv369/shippingservice
  newName: vicv369/shippingservice
  newTag: v34
- name: vicv369/shoppingassistantservice
  newName: vicv369/shoppingassistantservice
  newTag: v34
